platform :ios, '11.0'

target 'LoginTimetonicApp' do
  use_frameworks!
	pod 'PasswordTextField'

  # Pods for LoginTimetonicApp

  target 'LoginTimetonicAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginTimetonicAppUITests' do
    # Pods for testing
  end

end
